theme: jekyll-theme-architect

url: http://bruneo32.github.io/ANSI-Project
subtitle: Make quick ANSI formats to beautify terminal output
author: Bruno Castro Garcia
description: Make quick ANSI formats to beautify terminal output
email: bruneo32b@gmail.com
title-img: "/resources/logo.png"
